### ISSUE TITLE
CRS, GEOMETRY and OSM_ID graph attrubutes wrong format

### ISSUE THREAD

**Issue by GeorgeKontsevik** [aimclub/blocksnet#75]
Hi there is an issue with the type of crs properties at the intermodal graph. You are using class 'pyproj.crs.crs.CRS' which is not compatible with .graphml format. I suggest using int value (e.g. 4326 or 32636). If you get the crs value at your graph from GeoDataFrame using .crs --> it would be better to convert it to int value using .to_epsg(). The reason I am writing this is that I can't cache my graph to file to skip its repeated calculations when I reload my notebook.

This small change won't affect any part of the code since while creating a gdf from the graph you can use both options of crs system setting (pyproj class and int in recent versions of geopandas)

I think I might create a PR with the fix

**Comment by GeorgeKontsevik** [comment]
there is the same error with geometries in edge attributes. It is better to apply .wkt to each geometry to make it string type.

**Comment by GeorgeKontsevik** [comment]
There is also format problem with osmid in edge attributes. Somewhere it has list type, which is incompatible with .graphml format

**Comment by vasilstar97** [comment]
@GeorgeKontsevik hello, the graph made with ```GraphGenerator``` is OSMNX compatible, so the CRS is similar to GeoDataFrame CRS. You can load and save an obtained graph the following way:
```python
g = GraphGenerator.from_graphml('input.graphml')
...
GraphGenerator.to_graphml(g, 'output.graphml')
```
