### ISSUE TITLE
The accessibility matrix method

### ISSUE THREAD

**Issue by alexandermorozzov** [aimclub/blocksnet#76]
The accessibility matrix method does not accept as input transportation graphs assembled not in blocksnet.

**Comment by vasilstar97** [comment]
@alexandermorozzov, the validation for the city graph is upcoming in 0.0.3 pip version. So you have to keep up with specification:
```python
class GraphNode(BaseModel):
    x: float
    y: float


class GraphEdge(BaseModel):
    geometry: InstanceOf[LineString] = None
    weight: float = Field(ge=0)
    transport_type: Literal["walk", "drive", "subway", "tram", "bus", "trolleybus"]
```
As you can see the "distance" property is called weight, so it has to be float value greater or equal to 0
